### PR TITLE
Adjust procedures

### PR DESCRIPTION
**Pull request by mih**
- use `cfg_bids` from `-neuroimaging`
- rename `setup_hirni_dataset` -> `cfg_hirni` to match new conventions

### CODE REVIEW

**Comment by mih** [comment]
Hmm, does not find the procedure after -neuroimaging installation.

**Comment by bpoldrack** [comment]
Not yet. Most confusing to me: Happens for one test only, when it should happen for 5 or so, if it was about the installation.

**Comment by bpoldrack** [comment]
Somehow the wrong `-neuroimaging` is installed. Using `pip install git+https://github.com/datalad/datalad-neuroimaging.git` (as hirni should do via requirements) I get the same issue. Installing locally via `pip install -e .` wiht master checked out, however, works fine. Don't see the difference ATM.

**Comment by bpoldrack** [comment]
Don't get it. This doesn't work:
`pip install git+https://github.com/datalad/datalad-neuroimaging.git` although it is supposed to install from cloning master (adding `@master` doesn't help either).
Whereas this works:
`pip install -e git+https://github.com/datalad/datalad-neuroimaging.git#egg=datalad_neuroimaging`

To me this suggests, that the former still installs something not up to date. Can't figure why.

**Comment by bpoldrack** [comment]
Hm. Figured that `resources` aren't installed via the first call, whereas they are by the same call for `datalad-hirni`. With the second call it operates on the actual clone, so `resources` are available. Didn't spot any related difference between neuroimaging and hirni yet.

**Comment by bpoldrack** [comment]
FTR: Figured that `resources` aren't installed via the first call, whereas they are by the same call for `datalad-hirni`. With the second call it operates on the actual clone, so `resources` are available. Didn't spot any related difference between neuroimaging and hirni yet.

**Comment by mih** [comment]
Rebased on master.

**Pull request merged**
