### PR TITLE
Prepare release 0.0.5

### PR DESCRIPTION
**Pull request by bpoldrack**
This release should most importantly lead to compatibility with datalad 0.12.0rc6+, the lack thereof shown particularly in #129 and #150. Fix for that is in master already, release needs to make sure it's actually available, get dependencies right and include some minor fixes while at it.

### CODE REVIEW

**Comment by bpoldrack** [comment]
Remaining failure in two builds:

```
======================================================================

ERROR: datalad_hirni.tests.test_demos.test_demo_repro_analysis

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/home/travis/virtualenv/python3.5.6/src/datalad/datalad/tests/utils.py", line 156, in newfunc

    return func(*args, **kwargs)

  File "/home/travis/virtualenv/python3.5.6/src/datalad/datalad/tests/utils.py", line 727, in newfunc

    return t(*(arg + (filename,)), **kw)

  File "/home/travis/virtualenv/python3.5.6/src/datalad/datalad/tests/utils.py", line 727, in newfunc

    return t(*(arg + (filename,)), **kw)

  File "/home/travis/build/psychoinformatics-de/datalad-hirni/datalad_hirni/tests/test_demos.py", line 172, in test_demo_repro_analysis

    analysis_ds.containers_add('fsl', url="shub://ReproNim/ohbm2018-training:fsln")

  File "/home/travis/virtualenv/python3.5.6/src/datalad/datalad/distribution/dataset.py", line 526, in apply_func

    return f(**kwargs)

  File "/home/travis/virtualenv/python3.5.6/src/datalad/datalad/interface/utils.py", line 493, in eval_func

    return return_func(generator_func)(*args, **kwargs)

  File "/home/travis/virtualenv/python3.5.6/src/datalad/datalad/interface/utils.py", line 481, in return_func

    results = list(results)

  File "/home/travis/virtualenv/python3.5.6/src/datalad/datalad/interface/utils.py", line 412, in generator_func

    allkwargs):

  File "/home/travis/virtualenv/python3.5.6/src/datalad/datalad/interface/utils.py", line 528, in _process_results

    for res in results:

  File "/home/travis/virtualenv/python3.5.6/src/datalad-container/datalad_container/containers_add.py", line 223, in __call__

    imgurl = _resolve_img_url(url)

  File "/home/travis/virtualenv/python3.5.6/src/datalad-container/datalad_container/containers_add.py", line 42, in _resolve_img_url

    shub_info = loads(req.text)

  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/simplejson/__init__.py", line 525, in loads

    return _default_decoder.decode(s)

  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/simplejson/decoder.py", line 370, in decode

    obj, end = self.raw_decode(s)

  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/simplejson/decoder.py", line 400, in raw_decode

    return self.scan_once(s, idx=_w(s, idx).end())

simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
This appears to be an issue with loading JSON response from Singularity Hub. 
(`containers_add._resolve_img_url("shub://ReproNim/ohbm2018-training:fsln")`)

However, I cannot reproduce that locally and fail to see where my local env is different. Any chance that failure rings a bell, @kyleam?

**Comment by kyleam** [comment]
> Any chance that failure rings a bell, @kyleam?

No, sorry.  My wild guess is that it's due to Singularity Hub's download limits (in which case containers-add should of course give a more informative error).

**Comment by bpoldrack** [comment]
Thx, @kyleam ! Your guess seems not to far off. Tried again to reproduce from within `datalad-containers` tests only (by removing the skips due to shub "being down"). Got the same thing (additional logging capture says we got a 502) on first try, but can't reproduce again.

**Comment by bpoldrack** [comment]
And finally I made into debugger. It's 403 `You've done that too many times, try again tomorrow.`

**Pull request merged**
